# Generated by Django 2.0.7 on 2019-11-27 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CalorieData',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('calorie', models.IntegerField(default=0)),
                ('pub_date', models.DateField()),
            ],
        ),
    ]
